#!/bin/bash

cargo fmt --all && cargo clippy --workspace --tests --fix --allow-dirty

# Define a list names
FIRST_NAMES=("Cholmondeley" "Peregrine" "Montague" "Algernon" "Beauregard" "Rupert" "Crispin" "Basil" "Reginald" "Archibald" "Gianna" "Nella" "Franci" "Caty" "Lucietta" "Mariella" "Gabi" "Vale" "Rosina" "Giulietta" "Bea" "Sandra" "Isa" "Nora" "Chiaretta" "Sofi" "Raffa" "Paoletta" "Caro" "Sere")

# Define a list of surnames
SURNAMES=("Brock" "Urchin" "Beaver" "Cony" "Coney" "Hart" "Hind" "Stag" "Leveret" "Hobby" "Marten" "Polecat" "Wren" "Heron" "Bittern" "Allegro" "Adagio" "Andante" "Crescendo" "Diminuendo" "Forte" "Piano" "Legato" "Staccato" "Presto" "Lento" "Vivace" "Mezzo" "Sforzando" "Ritardando" "Accelerando" "Fortissimo" "Pianissimo" "Rubato" "Tempo")

# Define a list of surname prefixes
PREFIXES=("Mc" "Mac" "Saint" "Von" "O'" "De" "Fitz" "Le" "di" "" "" "" "")

# Generate random indices for the lists
RANDOM_FIRST_NAME=${FIRST_NAMES[$RANDOM % ${#FIRST_NAMES[@]}]}
RANDOM_SURNAME=${SURNAMES[$RANDOM % ${#ANIMALS[@]}]}
RANDOM_PREFIX=${PREFIXES[$RANDOM % ${#PREFIXES[@]}]}

# Combine to create a full name
RANDOM_SURNAME="$RANDOM_PREFIX$RANDOM_SURNAME"
FULL_NAME="$RANDOM_FIRST_NAME $RANDOM_SURNAME"

# Generate an email address
RANDOM_EMAIL="$(echo $FULL_NAME | tr ' ' '_' | tr '[:upper:]' '[:lower:]')@github.com"

# Set the author and committer information
git config user.name "$FULL_NAME"
git config user.email "$RANDOM_EMAIL"

# Output the selected author details
echo "Randomly generated author:"
echo "Name: $FULL_NAME"
echo "Email: $RANDOM_EMAIL"

exit 0
